//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaizen_Maintenance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMantenimiento
    {
        public int IdDetMantenimiento { get; set; }
        public int IdMantenimiento { get; set; }
        public string Nota { get; set; }
        public int IdEstado { get; set; }
    
        public virtual EstadoMantenimiento EstadoMantenimiento { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
    }
}
